---
- name: Cisco show version example-playbook
  hosts: switche
  gather_facts: false

  tasks:
    - name: run show version on remote devices
    cisco.ios.ios_command:
      commands: show version
    register: output

    - name: print output
      debug:
        var: output.stdout_lines