---
# tasks file for aci-configure-tenats
- name: Deploy topology using ACI model
  hosts: aci
  gather_facts: no
  connection: local

- name: create leaf interface access policy groups
  aci_rest:
    hostname: '{{ ansible_host }}'
    username: '{{ APIC_USERNAME }}'
    password: '{{ APIC_PASSWORD }}'
    path: /api/node/mo/uni.json
    method: post
    content: {
      "infraAcccPortGrp": {
        "attributes": {
          "annotation": "",
          "descr": "",
          "dn": "uni/infra/funcprof/accportgrp-Test1234",
          "name": "Test1234",
        }
      }
    }
    