---
# tasks file for aci-configure-tenats
- name: Set login credentials
  set_fact:
    aci_login: &aci_login
      hostname: '{{ ansible_host }}'
      username: '{{ APIC_USERNAME }}'
      password: '{{ APIC_PASSWORD }}'
      validate_certs: no


- name: create leaf interface access policy groups
  aci_rest:
    <<: *aci_login
    validate_certs: no
    path: /api/node/mo/uni.json
    method: post
    content: {
      "infraAccPortGrp": {
        "attributes": {
          "dn": "uni/infra/funcprof/accportgrp-TestJan",
          "name": "TestJan",
          "status": ""
        },
        "children": [
          {
            "infraRsStpIfPol": {
              "attributes": {
                "tnStpIfPolName": ""
              }
            }
          },
          {
            "infraRsStormctrlIfPol": {
              "attributes": {
                "tnStormctrlIfPolName": ""
              }
            }
          },
          {
            "infraRsMonIfInfraPol": {
              "attributes": {
                "tnMonInfraPolName": ""
              }
            }
          },
          {
            "infraRsMcpIfPol": {
              "attributes": {
                "tnMcpIfPolName": ""
              }
            }
          },
          {
            "infraRsMacsecIfPol": {
              "attributes": {
                "tnMacsecIfPolName": ""
              }
            }
          },
          {
            "infraRsAttEntP": {
              "attributes": {
                "tDn":  ""
              }
            }
          },
          {
            "infraRsCdpIfPol": {
              "attributes": {
                "tnCdpIfPolName": "Hallo"
              }
            }
          },
          {
            "infraRsL2IfPol": {
              "attributes": {
                "tnL2IfPolName": ""
              }
            }
          },
          {
            "infraRsCoppIfPol": {
              "attributes": {
                "tnCoppIfPolName": ""
              }
            }
          },
          {
            "infraRsLldpIfPol": {
              "attributes": {
                "tnLldpIfPolName": ""
              }
            }
          },
          {
            "infraRsFcIfPol": {
              "attributes": {
                "tnFcIfPolName": ""
              }
            }
          },
          {
            "infraRsHIfPol": {
              "attributes": {
                "tnFabricHIfPolName": ""
              }
            }
          },
          {
            "infraRsL2PortSecurityPol": {
              "attributes": {
                "tnL2PortSecurityPolName": ""
              }
            }
          }
        ]
        }
      }