---
# tasks file for aci-configure-tenats
- name: Set login credentials
  set_fact:
    aci_login: &aci_login
      hostname: '{{ ansible_host }}'
      username: '{{ APIC_USERNAME }}'
      password: '{{ APIC_PASSWORD }}'
      validate_certs: no


- name: create leaf interface access policy groups
  aci_rest:
    <<: *aci_login
    validate_certs: no
    path: /api/node/mo/uni.json
    method: post
    content: {
      "infraAcccPortGrp": {
        "attributes": {
          "annotation": "",
          "descr": "",
          "dn": "uni/infra/funcprof/accportgrp-Test1234",
          "name": "Test1234",
        }
      }
    }
    