---
# tasks file for aci-configure-leafs
- name: Set login credentials
  set_fact:
    aci_login: &aci_login
      hostname: '{{ ansible_host }}'
      username: '{{ APIC_USERNAME }}'
      password: '{{ APIC_PASSWORD }}'

- name: create leaf interface access policy groups
  aci_rest:
    <<: *aci_login
    path: /api/node/mo/uni.json
    method: post
    content: {
      "infraAccPortGrp": {
        "attributes": {
          "annotation": "",
          "descr": "",
          "dn": "uni/infra/funcprof/accportgrp-Test1234",
          "name": "Test1234",
        }
      }
    }